### PR TITLE
Support aarch64 with cibuildwheel==2.1.1

### PR DESCRIPTION
**Pull request by kimdwkimdw**
Need arm64 build like another libraries(ex. [matplotlib](https://pypi.org/project/matplotlib/#files)). @dofuuz

reference: https://github.com/pypa/cibuildwheel
https://github.com/matplotlib/matplotlib/blob/master/.github/workflows/cibuildwheel.yml#L11

### CODE REVIEW

**Comment by dofuuz** [comment]
Thank you for contribution.

I added ARM64 wheel with my code.
https://pypi.org/project/soxr/0.2.6/

Can you confirm it works for your needs?

**Comment by kimdwkimdw** [comment]
> Thank you for contribution.
> 
> I added ARM64 wheel with my code.
> https://pypi.org/project/soxr/0.2.6/
> 
> Can you confirm it works for your needs?

It works for arm64. thanks!

**Comment by dofuuz** [comment]
Sorry, I'm not going to merge this PR. 
ARM64 is added with other way😉 https://github.com/dofuuz/python-soxr/commit/a83eea0f8e38901a67b43f20270f01aa84ddb816
Anyway, now you can use soxr>=0.2.6 from pip with ARM64.

**Comment by kimdwkimdw** [comment]
Great! Thanks!

**Pull request closed without merging**
